### ISSUE TITLE
create and share first 10 exercises

### ISSUE THREAD

**Issue by timkock** [filippogallizia/firstprojectever#1]
Will use this issue to track work and comments on first 10 exercises for @filippogallizia

**Comment by filippogallizia** [comment]
@timkock can you push the other exercises referencing this commit so I know when they are there? Can you also specify which exercises there will be? Make sure there are 10 in total so I can close this issue when committing my answers 👯

**Comment by timkock** [comment]
Exercises plan is finalised @filippogallizia . These will be first 10 exercises.
When checked the exercise has been committed.

- [x] **E01** check even/odd numbers in array
- [x] **E02** implement bubble-sort (bonus: ascending and descending order)
- [x] **E03** zip two arrays (k, v) into array of objects (bonus: into one object)
- [x] **E04** turn an array of strings into song lines evenly boxed in a formatted output
- [x] **E05** ceasar cipher (bonus: encrypt numbers too, ultrabonus: encrypt numbers and letters interchangeably)
- [ ] **E06** hack a ceasar cipher given a couple of intercepted strings (bonus: make a blog post out of it)
- [ ] **E07** ultra object manipulation challenge, several object mini tasks to show flex on objects
- [ ] **E08** make a pretty printed calendar and highlight certain dates (bonus: tbd)
- [ ] **E09** implement a small database (bonus: persistence to disk)
- [ ] **E10** implement battleships game in javascript terminal (bonus: website multiplayer implementation)
